from enum import Enum

__NAMESPACE__ = "http://www.movielabs.com/schema/md/v2.8/md"


class StringAudioEncChannelMapping(Enum):
    VALUE_5_1_MATRIX = "5.1 Matrix"
    VALUE_6_1_MATRIX = "6.1 Matrix"
    CENTER_SURROUND = "Center surround"
    CENTER = "Center"
    DUAL_MONO = "dual mono"
    IMAX_6_0 = "IMAX 6.0"
    IMAX_6_1 = "IMAX 6.1"
    IMAX_12_0 = "IMAX 12.0"
    IMAX_12_1 = "IMAX 12.1"
    L_C_R_LS_RS_LFE = "L,C,R,LS,RS,LFE"
    L_R_C_LFE_LS_RS = "L,R,C,LFE,LS,RS"
    LFE_2 = "LFE 2"
    LFE_SCREEN = "LFE screen"
    LEFT_CENTER = "Left center"
    LEFT_SURROUND_DIRECT = "Left surround direct"
    LEFT_SURROUND = "Left surround"
    LEFT_TOP_FRONT_SURROUND = "Left Top Front Surround"
    LEFT_TOP_REAR_SURROUND = "Left Top Rear Surround"
    LEFT_WIDE = "Left wide"
    LEFT = "Left"
    REAR_SURROUND_LEFT = "Rear surround left"
    REAR_SURROUND_RIGHT = "Rear surround right"
    RIGHT_CENTER = "Right center"
    RIGHT_SURROUND_DIRECT = "Right surround direct"
    RIGHT_SURROUND = "Right surround"
    RIGHT_TOP_FRONT_SURROUND = "Right Top Front Surround"
    RIGHT_TOP_REAR_SURROUND = "Right Top Rear Surround"
    RIGHT_WIDE = "Right wide"
    RIGHT = "Right"
    STEREO = "stereo"
    SURROUND = "surround"
    TOP_CENTER_SURROUND = "Top center surround"
    VERTICAL_HEIGHT_FRONT = "Vertical height front"
