from enum import Enum

__NAMESPACE__ = "http://www.movielabs.com/schema/md/v2.8/md"


class StringVideoEncCodec(Enum):
    AVI_UNCOMPRESSED = "AVI Uncompressed"
    CINE_FORM_HD = "CineForm HD"
    DIVX = "DIVX"
    DV = "DV"
    H_264 = "H.264"
    H_264_DOLBY_VISION = "H.264-DolbyVision"
    H_265 = "H.265"
    H_265_DOLBY_VISION = "H.265-DolbyVision"
    JPEG2000 = "JPEG2000"
    MOBICLIP = "MOBICLIP"
    MPEG1 = "MPEG1"
    MPEG2 = "MPEG2"
    ON2 = "On2"
    PHOTOJPEG = "PHOTOJPEG"
    PRORES = "PRORES"
    PRORES422 = "PRORES422"
    PRORES4444 = "PRORES4444"
    PRORESHQ = "PRORESHQ"
    PRORESXQ = "PRORESXQ"
    QT_UNCOMPRESSED = "QT Uncompressed"
    REAL = "REAL"
    SVQ = "SVQ"
    SPARK = "Spark"
    VC_2 = "VC-2"
    VC_3 = "VC-3"
    VC_5 = "VC-5"
    VC_6 = "VC-6"
    VC1 = "VC1"
    VP6 = "VP6"
    VP7 = "VP7"
    VP8 = "VP8"
    VP9 = "VP9"
    WMV = "WMV"
    WMV7 = "WMV7"
    WMV8 = "WMV8"
    WMV9 = "WMV9"
    XVID = "XVID"
    OTHER = "OTHER"
