from enum import Enum

__NAMESPACE__ = "http://www.movielabs.com/schema/md/v2.8/md"


class StringContainerType(Enum):
    VALUE_3_GP = "3GP"
    VALUE_3_GP2 = "3GP2"
    AC3 = "AC3"
    AIFF = "AIFF"
    ASF = "ASF"
    AVI = "AVI"
    ATMOS = "atmos"
    CFF = "CFF"
    DAMF = "DAMF"
    DIVX = "DIVX"
    DTS = "DTS"
    FLV = "FLV"
    HCT = "HCT"
    IMF = "IMF"
    ISO = "ISO"
    JPEG = "JPEG"
    M4_V = "M4V"
    MJ2 = "MJ2"
    MKV = "MKV"
    MP4 = "MP4"
    MPEG_2_PS = "MPEG-2 (PS)"
    MPEG_2_TS = "MPEG-2 (TS)"
    MXF = "MXF"
    OGG = "Ogg"
    PNG = "PNG"
    QUICKTIME_MOV = "Quicktime (MOV)"
    RIFF = "RIFF"
    RM = "RM"
    SWF = "SWF"
    TIFF = "TIFF"
    VOB = "VOB"
    WAV = "WAV"
    WMV = "WMV"
    XMF = "XMF"
    ZIP = "ZIP"
    OTHER = "Other"
