from enum import Enum

__NAMESPACE__ = "http://www.movielabs.com/schema/md/v2.8/md"


class StringVideoEncMprofile(Enum):
    SP = "SP"
    MP = "MP"
    SNR = "SNR"
    SPATIAL = "Spatial"
    HP = "HP"
    VALUE_422 = "422"
    MVP = "MVP"
    BP = "BP"
    CBP = "CBP"
    XP = "XP"
    HI_P = "HiP"
    CHI_P = "CHiP"
    PHI_P = "PHiP"
    HI10_P = "Hi10P"
    HI422_P = "Hi422P"
    HI444_P = "Hi444P"
    HI444_PP = "Hi444PP"
    HI10_IP = "Hi10IP"
    HI422_IP = "Hi422IP"
    HI444_IP = "Hi444IP"
    C444_IP = "C444IP"
    SBP = "SBP"
    SCBP = "SCBP"
    SHP = "SHP"
    SHIP = "SHIP"
    SCHP = "SCHP"
    STEREO_HP = "StereoHP"
    MULTIVIEW_HP = "MultiviewHP"
