from enum import Enum

__NAMESPACE__ = "http://www.movielabs.com/schema/md/v2.8/md"


class StringAudioEncCodec(Enum):
    AAC = "AAC"
    AAC_LC = "AAC-LC"
    AAC_LC_MPS = "AAC-LC+MPS"
    AAC_SLS = "AAC-SLS"
    AC_3 = "AC-3"
    AC_4 = "AC-4"
    ADMBWF = "ADMBWF"
    AIFF = "AIFF"
    ALAC = "ALAC"
    AMR = "AMR"
    BWF = "BWF"
    BWF_RF64 = "BWF-RF64"
    DAMF = "DAMF"
    DOLBY_ATMOS_ADMBWF = "DOLBY-ATMOS-ADMBWF"
    DOLBY_DDPLUS_ATMOS = "DOLBY-DDPLUS-ATMOS"
    DOLBY_TRUEHD = "DOLBY-TRUEHD"
    DSD = "DSD"
    DST = "DST"
    DTS = "DTS"
    DTS_ES = "DTS-ES"
    DTS_EXPRESS = "DTS-EXPRESS"
    DTS_HRA = "DTS-HRA"
    DTS_96_24 = "DTS-96/24"
    DTS_MA = "DTS-MA"
    DTS_X = "DTS-X"
    DTS_X_ADMBWF = "DTS-X-ADMBWF"
    E_AC_3 = "E-AC-3"
    FLAC = "FLAC"
    HE_AACV2 = "HE-AACv2"
    IAB = "IAB"
    LPAC = "LPAC"
    LTAC = "LTAC"
    MP3 = "MP3"
    MPEG1 = "MPEG1"
    MPEG_4_ALS = "MPEG-4-ALS"
    MPEG_H = "MPEG-H"
    MLP = "MLP"
    PCM = "PCM"
    QCELP = "QCELP"
    REAL_AUDIO_LOSSLESS = "RealAudio-Lossless"
    VORBIS = "Vorbis"
    WAV = "WAV"
    WMA = "WMA"
    WM9_LOSSLESS = "WM9-Lossless"
    OTHER = "Other"
