from enum import Enum

__NAMESPACE__ = "http://www.eidr.org/schema"


class EditClassType(Enum):
    """
    These are intended to enumerate the primary, distinguishing characteristics of
    the Edit.
    """

    ALTERNATE_ENDING = "Alternate Ending"
    ANNIVERSARY = "Anniversary"
    CENSORED = "Censored"
    COLORIZED = "Colorized"
    CONTENT_BREAK = "Content Break"
    CREATIVE = "Creative"
    CREDITS = "Credits"
    DIALOG = "Dialog"
    DIRECTOR_S_CUT = "Director's Cut"
    DUBBING_CREDITS = "Dubbing Credits"
    EXIT = "Exit"
    EXTENDED = "Extended"
    INTERACTIVE_PLATFORM = "Interactive Platform"
    INTERMISSION = "Intermission"
    LOGOS = "Logos"
    MUSIC = "Music"
    ORIGINAL = "Original"
    OVERTURE = "Overture"
    PRODUCT_PLACEMENT = "Product Placement"
    PROMOTIONAL = "Promotional"
    RECAP = "Recap"
    REGIONALIZED = "Regionalized"
    RERELEASED = "Rereleased"
    RESTORED_AUDIO = "Restored Audio"
    RESTORED_PICTURE = "Restored Picture"
    RESTORED = "Restored"
    SANITIZED_AUDIO = "Sanitized Audio"
    SANITIZED_PICTURE = "Sanitized Picture"
    SANITIZED = "Sanitized"
    SHORTENED = "Shortened"
    SOUND_EFFECTS = "Sound Effects"
    SPLIT = "Split"
    SUBSTITUTIONS = "Substitutions"
    SYNDICATION = "Syndication"
    TEXTLESS = "Textless"
    THREE_D = "Three-D"
    UNRATED = "Unrated"
    OTHER = "Other"
