import json
from enum import Enum
from optparse import Option
from textwrap import dedent
from types import NoneType
from typing import Optional, Set, get_type_hints, get_origin, Union, get_args, List, Tuple, Any, Type, Dict
import re
from urllib.parse import uses_params

from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig
from xsdata.models.datatype import XmlDate, XmlPeriod, XmlDuration

import app.scheme.org.eidr.schema
from app.scheme.org.eidr.schema import SimpleInfo, ExtraObjectMetadataType, QueryType

from dataclasses import make_dataclass, field, fields, is_dataclass

from app.services import Query, ResponseReader
from app.driver import API_Driver


import inspect


def attempt(func):
    try:
        return func(), None
    except Exception as e:
        return None, e

def is_optional_type(t) -> bool:
    # Check if the type is a Union (which Optional is)
    if get_origin(t) is Union:
        args = get_args(t)
        # Check if one of the Union arguments is None
        return type(None) in args
    return False

def get_optional_inner_type(t):
    if is_optional_type(t):
        args = get_args(t)
        # Return the first non-None type (e.g., Optional[int] -> int)
        return next(a for a in args if a is not type(None))
    return None

def get_type_name(t: type) -> str:
    if get_origin(t) is Union:
        args = get_args(t)
        if len(args) == 2 and type(None) in args:
            inner = next(a for a in args if a is not type(None))
            return f"Optional[{get_type_name(inner)}]"
    return getattr(t, "__name__", str(t))


allowed_types: Set[type] = {
    str, int, float, bool, type(None), Enum, Optional[str], Optional[int], Optional[float],
    Optional[bool], Union[XmlPeriod, XmlDate, NoneType], XmlPeriod, XmlDate, XmlDuration
}


## Converts a class (intended for autogenerated dataclasses) into a dict
## Includes type information for each field with added "_type" suffix
##      ex: "compilation_info" will come with "compilation_info_type"
##      This can be used to serialize the object into XML, or to provide type information
## Types not in allowed_types (above) are recursed into dictionaries as well
## The default_enums flag decides whether an enum's first value is used as the default, instead of ""
## The include_xml flag decides whether the XML string is included in the output
##      "_xml_" will be the key, and the XML string will be the value
##      !!! WIP
def to_field_dict(cls, default_enums = True, include_xml = True) -> dict | str:
    hints = get_type_hints(cls)
    name = cls.__name__

    out = {}
    if is_dataclass(cls) and include_xml:
        out["_xml_"] = generate_xml(cls)
    if issubclass(cls, Enum): # Handle enum case (only need a string out)
        out = list(cls)[0].value if default_enums else ""
    elif cls in allowed_types:
        return generate_default(cls)

    for member, _type in hints.items():
        # Happy case, no special handling needed
        if _type in allowed_types:
            # Preserve hinted types (i.e. Optional[str] instead of None or str)
            if is_optional_type(_type):
                inner_type = get_optional_inner_type(_type)
                out[member] = generate_default(inner_type)
                out[member + "_type"] = inner_type
            else:
                out[member] = generate_default(_type)
                out[member + "_type"] = _type
        else:
            if get_origin(_type) is list:
                inner_type = get_args(_type)[0]
                if inner_type not in allowed_types:
                    obj_dict = to_field_dict(inner_type)
                    out[member] = [obj_dict]
                else:
                    out[member] = []
                out[member + "_type"] = List[inner_type]
            else:
                if is_optional_type(_type):
                    inner = to_field_dict(get_optional_inner_type(_type))
                    out[member + "_type"] = _type
                else:
                    inner = to_field_dict(_type)
                out[member] = inner
                out[member + "_type"] = _type

    return out


default_map: Dict[type, Any] = {
    XmlPeriod: "1999-10+03:30",
    XmlDate: "1970-01-01",
    XmlDuration: "P2Y6M5DT12H",
    int: 0,
    NoneType: None,
}

## Create an instance of a dataclass with default values, including for nested dataclasses
def default_dataclass(cls):
    if not is_dataclass(cls):
        return cls
    if cls in default_map:
        return cls(default_map[cls])
    if len(cls.__init__.__code__.co_varnames) == 1:
        return cls()
    else:
        return cls(*(default_dataclass(getattr(cls, field.name)) for field in fields(cls)))



def generate_default(cls):
    sig = inspect.signature(cls.__init__)
    if len(sig.parameters) == 0:
        return cls()
    if cls in default_map:
        return cls(default_map[cls])
    return cls("")

serializer = XmlSerializer(config=SerializerConfig(pretty_print_indent="    ", xml_declaration=False))
ns_map = {"": "http://www.eidr.org/schema"}
def generate_xml(cls):
    xml_str = serializer.render(cls(), ns_map)
    return xml_str

def filter_type_info(d: dict, substr: str = "_type"):
    out = {}
    for key, value in d.items():
        if isinstance(value, dict):
            out[key] = filter_type_info(value, substr)
        elif isinstance(value, list):
            out[key] = []
            for item in value:
                if isinstance(item, dict):
                    out[key].append(filter_type_info(item, substr))
                else:
                    out[key].append(item)
        elif substr not in key:
            out[key] = value

    return out


non_serials = {XmlPeriod, XmlDate, XmlDuration}
def repr_non_serials(d: dict):
    out = {}
    for key, value in d.items():
        if isinstance(value, dict):
            out[key] = repr_non_serials(value)
        elif isinstance(value, list):
            out[key] = []
            for item in value:
                if isinstance(item, dict):
                    out[key].append(repr_non_serials(item))
                else:
                    out[key].append(item)
        elif type(value) in non_serials:
            out[key] = str(value)
        else:
            out[key] = value

    return out

if __name__ == "__main__":
    # Test the RegistryHandler
    # Example usage
    indents = 4
    out = to_field_dict(Query)
    print(json.dumps(repr_non_serials(filter_type_info(out)), indent=indents))





