from enum import Enum

__NAMESPACE__ = "http://www.eidr.org/schema"


class TimeZoneType(Enum):
    """
    Primary standard timezone for a service.
    """

    IDLW = "IDLW"
    NUT = "NUT"
    HST = "HST"
    MIT = "MIT"
    AKST = "AKST"
    PST = "PST"
    MST = "MST"
    CST = "CST"
    EST = "EST"
    AST = "AST"
    NST = "NST"
    BRT = "BRT"
    FNT = "FNT"
    CVT = "CVT"
    UTC = "UTC"
    GMT = "GMT"
    WAT = "WAT"
    CET = "CET"
    EET = "EET"
    MSK = "MSK"
    IRST = "IRST"
    GST = "GST"
    AFT = "AFT"
    PKT = "PKT"
    IST = "IST"
    NPT = "NPT"
    BST = "BST"
    CCT = "CCT"
    MMT = "MMT"
    THA = "THA"
    SGT = "SGT"
    AWST = "AWST"
    JST = "JST"
    ACST = "ACST"
    AEST = "AEST"
    LHST = "LHST"
    NCT = "NCT"
    NZST = "NZST"
    CHAST = "CHAST"
    TOT = "TOT"
    LINT = "LINT"
